config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users 
  resources :groups do
    resources :spendings
  end

  resources :spendings
  root 'homes#index'
  # root 'groups#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :spendings, dependent: :delete_all
  belongs_to :author, class_name: 'User'

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true, length: { maximum: 250 }
end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :group
  belongs_to :author, class_name: 'User'

  validates :amount, presence: true
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :delete_all
  has_many :spendings, dependent: :delete_all

  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end

  # # Catch all CanCan errors and alert the user of the exception
  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    # return unless current_user

    # @author = current_user
    # @groups = @author.groups.includes(:spendings)

    @groups = Group.all
  end

  def show
    @spendings = @group.spendings.order('created_at DESC')
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.author_id = current_user.id
    # render :new unless @group.save
    @group.save
    redirect_to group_path(@group)
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Category was successfully deleted!' }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  def new
    @spending = Spending.new
  end

  def create
    @groups = params[:spending][:group_id].drop(1)
    @groups.each do |group|
      @spending = Spending.new(name: params[:spending][:name], amount: params[:spending][:amount],
                               group_id: group.to_i, author_id: current_user.id)
      @spending.save
    end
    redirect_to group_path(@groups.first.to_i)
  end

  private

  def spending_params
    params.require(:spending).permit(:group_id, :amount, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/views/groups/_form.html.erb
<div class="container-fluid w-100 d-flex flex-column align-items-center mt-2">
  <%= form_with model: @group, url: groups_path, method: :post, :html => {:class => "w-75 mt-4"} do |form| %>
    <div class="form-floating mb-3 w-100">
      <%= form.text_field :name, class:"form-control", id:"floatingInput", placeholder:"Category name" %>
      <%= form.label :name, 'Name', class: "form-label" %>
    </div>
    <div class="form-floating mb-3 w-100">
      <%= form.text_field :icon, class:"form-control", id:"floatingInput", placeholder:"Category icon"  %>
      <%= form.label :icon, 'Icon link', class: "form-label" %>
    </div>
    <%= form.submit 'Create category', class: "btn btn-warning text-white" %>
  <% end %>
</div>

<br>
<%= link_to "Back",groups_path, class:"btn btn-primary text-white" %>
<br><br>

app/views/groups/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<br><div class="container"  align="center">
    <h2>All Categories</h2>

<%= link_to "Create Category",new_group_path, class:"btn btn-warning text-white" %>

<% @groups.each do |group| %>
<a href="/groups/<%= group.id %>" class = 'user-clickable'>

<div class="category_show">
 <h2><%= group.name%></h2>
 <img src= <%= group.icon %> /><br>
 <%= group.created_at %>
 </div>
</a>

<% end %>

</div><br><br>

app/views/groups/new.html.erb
<br><div class="container"  align="center">

<h1> create a category! </h1>
<%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<br><div class="container"  align="center">
<div class="container-fluid d-flex flex-column align-items-center ">
  <div class="card" style="width: 95%;">
    <div class="card-header">
      <div class="d-flex align-items-center category_show_content">
        <img src=<%= @group.icon %> class="category-icon me-4" alt="category icon">
        <h5 class="card-title category-name fs-5 stretched-link"><%=@group.name%>'s transactions</h5>
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between bg-light">
        <p class="m-1 gray-text fs-5">TOTAL PAYMENT</p>
        <p class="fw-semibold m-1 gray-text fs-5">$<%= @spendings.sum(:amount) %></p>
      </li>
      <% unless @spendings.empty? %>
        <% @spendings.each_with_index do |spen, idx| %>
          <li class="list-group-item">
            <div d-flex flex-column>
              <p class="card-text gray-text">Transaction N°<%=idx + 1%>: <span class="fw-semibold ms-2"><%=spen.name%></span></p>
              <p class="card-text gray-text">Amount: <span class="fw-semibold ms-2">$<%=spen.amount%></span></p>
              <p class="card-text mt-2"><small class="text-muted"><i class="fa-regular fa-calendar me-2"></i><%=spen.created_at.strftime("%d %b %Y")%> at <%=spen.created_at.strftime("%I.%M %p")%></small></p>
            </div>
          </li>
        <% end %>
      <% else %>
        <li class="list-group-item gray-text">You don't have transactions here yet.</li>
      <% end %>
    </ul>
  </div>
  <%= link_to 'Add a new transaction', new_spending_path, class: "btn btn-warning my-5 py-2 px-5 text-white fs-6" %>
</div>
<hr>
<%= link_to "Back",groups_path, class:"btn btn-primary text-white" %>
<%= link_to "Create Category",new_group_path, class:"btn btn-warning text-white" %><br><br>

</div>

app/views/homes/index.html.erb
<%= image_tag ("anime.jpg"), class:"image"%>
<div class="container btns_container">
    <%= link_to "Sign In", new_user_session_path, class:"btn btn-warning " %>
    <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-warning" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TouhaBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>


   <% if user_signed_in? %>
    <%# navbar %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="https://github.com/TahenyBELGUITH">TouHaX</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mt-4 mb-lg-0">

         <li class="nav-item me-1">
          <h4><%= link_to "Create Transaction", new_spending_path, class:" btn btn-warning text-white", aria_current:"page"%></h4>
        </li><br>

        <li class="nav-item me-1">
          <h4><%= link_to "Categories", groups_path, class:"btn btn-warning text-white", aria_current:"page"%></h4>
        </li>
<br>

        <li class="nav-item me-1">
          <h4><%= link_to "Create Category",new_group_path, class:"btn btn-warning text-white" %>
          </h4>
        </li><br>

      </ul>
      <br>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-danger"  %>
    </div>
    <% end %>  
  </div>
</nav>
  <%# end %>

    <%= yield %>

    
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/spendings/_form.html.erb
<div class="container-fluid w-100 d-flex flex-column align-items-center ">
  <%= form_with model: @spending, url: spendings_path, method: :post, :html => {:class => "w-75 mt-4"} do |form| %>
    <div class="form-floating mb-2 w-100">
      <%= form.text_field :name, class:"form-control", id:"floatingInput", placeholder:"Transaction name" %>
      <%= form.label :name, 'Name', class: "form-label" %>
    </div>
    <div class="form-floating mb-2 w-100">
      <%= form.number_field :amount, class:"form-control", id:"floatingInput", placeholder:"Transaction amount"  %>
      <%= form.label :amount, 'Amount', class: "form-label" %>
    </div>
    <%= form.label :group_id, 'Please select a category:', class: "form-label" %>
    <%= form.select :group_id, Group.order(:name).where(author:current_user).pluck(:name, :id), {}, {:multiple => true, required:true, :id => "groups", :class => "form-select mb-3" } %>
    <%= form.submit 'Create transaction', class: "btn btn-warning text-white" %>
  <% end %>
</div><br><br>

app/views/spendings/new.html.erb
<br><div class="container" align="center">
<h1>Add transaction</h1>
<%= render 'form', spending: @spending %>
</div>